title: WTD Learning Material
description: All learning material to support our learning community
theme: just-the-docs

url: https://github.com/whiletrue-do/WTD_learning_material

aux_links:
  WTD Learning Github: https://github.com/whiletrue-do/WTD_learning_material

logo: "/assets/ima/just-the-docs.png"

favicon_ico: "/assets/images/favicon.ico"