title: WTD Learning Material
description: All learning material to support our learning community
theme: just-the-docs

url: https://github.com/whiletrue-do/WTD_learning_material

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
